# Notes on previously visited locations

## Overview

This document provides a listing of previously visited locations and some reminders on how to navigate them.
I will not list London, Hong Kong or Sydney/Melbourne, as I visit these places often enough that it doesn't matter.

## America

**Seattle:** 
There is a train from the airport running into the city, costing 3 USD either way.

**San Francisco:** 
Not really sure how to get around, as I got a pre-booked driver to take me to Stanford (and back).

**Boston:** 
A bus-like thing will go to South Station in the middle of the city.
It is free going in but costs 2.5 USD to go back to the airport.

## Europe

**Valencia:**
Driven by colleagues.

**Faro:**
Driven by colleagues.

**Nice:**
Driven by hosts.

**Paris:**
The Eurostar arrives in Gare du Nord, which is a pretty _meh_ part of town.

## Middle East

**Tel Aviv:**
There is an official taxi queue on the ground level.
It costs 120 shekels to go to Rehovot (for four people with luggage).
